### ISSUE TITLE
error trying to install/run

### ISSUE THREAD

**Issue by mgaulton** [loomchild/puffin#2]
I got the message before restart when trying "docker-machine create -d virtualbox dev". reboot didn't work for me on opensuse 13.2

I had to do a is sudo modprobe vboxnetadp then VirtualBox restart but its now giving me the message after noted below

Message before restart
derr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterface, interface IHostNetworkInterface
VBoxManage: error: Context: "int handleCreate(HandlerArg*, int, int*)" at line 66 of file VBoxManageHostonly.cpp

Message after
server6:~ # docker-machine create -d virtualbox dev
Running pre-create checks...
Creating machine...
Error creating machine: Error in driver during machine creation: exit status 1

**Comment by loomchild** [comment]
Hi, I think your problem is related to VirtualBox, your OS or your hardware configuration, please try to seek help there.
